# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64beaa36c6f8a0d7a97ec24cff0b4ccd5618a93c3db5a2eda0a2c8c1b810fc7a4ee365310f75786d300b8d668306be2b81aa2c8b05ec3e78e87a91c21945ad30

test:
  secret_key_base: 8f6bf53bce122dbe9250fc946bfd4b6f89a959c48768aeaf9afc968b6fd58c422424a7f17652e45a6172471c90d08f788acb80bd36106c5bb2100b263370914b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
